[package]
name = "stress"
version = "0.1.0"
authors = ["Joel Dice <joel.dice@gmail.com>"]

[dependencies]
tokio = "*"
hyper = "*"
hyper-tls = "*"
native-tls = "*"
futures = "0.1"
clap = "*"
log = "*"
pretty_env_logger = "*"
failure = "*"
